version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "A hello world !"
          command: echo "Hello world !"
      - add_ssh_keys:
          fingerprints:
            - "59:56:5d:ba:e8:6d:90:a8:2d:7d:0e:41:d8:60:c6:1c"

      - run:
          name: "Cloning private repo"
          command: git clone git@github.com:taoufik07/ensat-framework.git


