version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "A hello world !"
          command: echo "Hello world !"

      - run:
          name: "Building the image"
          command: |
            docker build --build-arg SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)" -t taoufik07/cython_obfuscate .

      - run:
          name: "Remove intermediate container"
          command: docker rmi -f $(docker images -q --filter label=stage=building_optimizer)

